name: CMake

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Get GCC-12
      run:   |
             sudo apt update && sudo apt upgrade -y
             sudo apt install -y cmake
             sudo apt install -y doxygen

    - name: CMake configuration
      run:  >
        cmake 
        -B ${{github.workspace}}/build 
        -S .
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: CMake build
      run:  >
        cmake 
        --build ${{github.workspace}}/build 
        --config ${{env.BUILD_TYPE}}

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html